Traceback (most recent call last):
  File "/Users/jiangsai/Downloads/Python脚本/reminder.py", line 104, in <module>
    main_loop(params)
  File "/Users/jiangsai/Downloads/Python脚本/reminder.py", line 82, in main_loop
    asyncio.run(speak(f"{ch_time}"))
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jiangsai/Downloads/Python脚本/reminder.py", line 37, in speak
    await communicate.save("output.mp3")
  File "/opt/anaconda3/lib/python3.12/site-packages/edge_tts/communicate.py", line 507, in save
    async for message in self.stream():
  File "/opt/anaconda3/lib/python3.12/site-packages/edge_tts/communicate.py", line 483, in stream
    async for message in self.__stream():
  File "/opt/anaconda3/lib/python3.12/site-packages/edge_tts/communicate.py", line 352, in __stream
    ) as session, session.ws_connect(
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/aiohttp/client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 503, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&Sec-MS-GEC=549530C92DB686CE4A45626E52B72DF19F1D5D9D0B81204A256A8B73B28F27FA&Sec-MS-GEC-Version=1-130.0.2849.68&ConnectionId=6374d375b1c04a00a8d25ebc3ead5e23'
